package br.com.aula;
// Generated 01/12/2015 15:58:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

    private Integer id;
    private String nome;
    private String local;
    private String descricao;
    private Set funcionarios = new HashSet(0);

    public Departamento() {
    }

    public Departamento(String nome, String local, String descricao, Set funcionarios) {
        this.nome = nome;
        this.local = local;
        this.descricao = descricao;
        this.funcionarios = funcionarios;
    }

    public Departamento(Integer id, String nome, String local, String descricao) {
        this.id = id;
        this.nome = nome;
        this.local = local;
        this.descricao = descricao;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set getFuncionarios() {
        return this.funcionarios;
    }

    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }

}
