package br.com.aula;
// Generated 01/12/2015 15:58:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

    private Integer id;
    private String nome;
    private String cnpj;

    public Empresa() {
    }

    public Empresa(Integer id, String nome, String cnpj) {
        this.id = id;
        this.nome = nome;
        this.cnpj = cnpj;
    }

    public Empresa(String nome, String cnpj) {
        this.nome = nome;
        this.cnpj = cnpj;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCnpj() {
        return cnpj;
    }

    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

}
