package br.com.aula;
// Generated 03/12/2015 08:17:40 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Folha generated by hbm2java
 */
public class Folha implements java.io.Serializable {

    private Integer id;
    private Empresa empresa;
    private Funcionario funcionario;
    private BigDecimal inss;
    private BigDecimal sindicato;
    private BigDecimal ajudacusto;
    private BigDecimal plr;
    private BigDecimal decimo;
    private Integer periodo;
    private String ferias;
    private Date datapagamento;
    private String salariofamilia;
    private BigDecimal salario;

    public Folha() {
    }

    public Folha(Empresa empresa, Funcionario funcionario) {
        this.empresa = empresa;
        this.funcionario = funcionario;
    }

    public Folha(Integer id, Empresa empresa, Funcionario funcionario, BigDecimal inss, BigDecimal sindicato, BigDecimal ajudacusto, BigDecimal plr, BigDecimal decimo, Integer periodo, String ferias, Date datapagamento, String salariofamilia, BigDecimal salario) {
        this.id = id;
        this.empresa = empresa;
        this.funcionario = funcionario;
        this.inss = inss;
        this.sindicato = sindicato;
        this.ajudacusto = ajudacusto;
        this.plr = plr;
        this.decimo = decimo;
        this.periodo = periodo;
        this.ferias = ferias;
        this.datapagamento = datapagamento;
        this.salariofamilia = salariofamilia;
        this.salario = salario;
    }

    public Folha(Empresa empresa, Funcionario funcionario, BigDecimal inss, BigDecimal sindicato, BigDecimal ajudacusto, BigDecimal plr, BigDecimal decimo, Integer periodo, String ferias, Date datapagamento, String salariofamilia, BigDecimal salario) {
        this.empresa = empresa;
        this.funcionario = funcionario;
        this.inss = inss;
        this.sindicato = sindicato;
        this.ajudacusto = ajudacusto;
        this.plr = plr;
        this.decimo = decimo;
        this.periodo = periodo;
        this.ferias = ferias;
        this.datapagamento = datapagamento;
        this.salariofamilia = salariofamilia;
        this.salario = salario;

    }

    public BigDecimal getSalario() {
        return salario;
    }

    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public BigDecimal getInss() {
        return this.inss;
    }

    public void setInss(BigDecimal inss) {
        this.inss = inss;
    }

    public BigDecimal getSindicato() {
        return this.sindicato;
    }

    public void setSindicato(BigDecimal sindicato) {
        this.sindicato = sindicato;
    }

    public BigDecimal getAjudacusto() {
        return this.ajudacusto;
    }

    public void setAjudacusto(BigDecimal ajudacusto) {
        this.ajudacusto = ajudacusto;
    }

    public BigDecimal getPlr() {
        return this.plr;
    }

    public void setPlr(BigDecimal plr) {
        this.plr = plr;
    }

    public BigDecimal getDecimo() {
        return this.decimo;
    }

    public void setDecimo(BigDecimal decimo) {
        this.decimo = decimo;
    }

    public Integer getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    public String getFerias() {
        return this.ferias;
    }

    public void setFerias(String ferias) {
        this.ferias = ferias;
    }

    public Date getDatapagamento() {

        return datapagamento;
    }

    public void setDatapagamento(Date datapagamento) {
        this.datapagamento = datapagamento;
    }

    public String getSalariofamilia() {
        return salariofamilia;
    }

    public void setSalariofamilia(String salariofamilia) {
        this.salariofamilia = salariofamilia;
    }

}
