package br.com.aula;
// Generated 01/12/2015 15:58:00 by Hibernate Tools 4.3.1

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario implements java.io.Serializable {

    private Integer id;
    private Departamento departamento;
    private String nome;
    private String funcao;
    private String registro;
    private String cpf;
    private String fumante;
    private String pai;
    private String mae;

    public Funcionario() {
        
    }
    

    public Funcionario(Integer id, Departamento departamento, String nome, String funcao, String registro, String cpf, String fumante, String pai, String mae) {
        this.id = id;
        this.departamento = departamento;
        this.nome = nome;
        this.funcao = funcao;
        this.registro = registro;
        this.cpf = cpf;
        this.fumante = fumante;
        this.pai = pai;
        this.mae = mae;
    }

    public Funcionario(Departamento departamento) {
        this.departamento = new Departamento();
    }
    
    

    public Funcionario(Departamento departamento, String nome, String funcao, String registro, String cpf, String fumante, String pai, String mae) {
        this.departamento = departamento;
        this.nome = nome;
        this.funcao = funcao;
        this.registro = registro;
        this.cpf = cpf;
        this.fumante = fumante;
        this.pai = pai;
        this.mae = mae;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getFuncao() {
        return this.funcao;
    }

    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }

    public String getRegistro() {
        return this.registro;
    }

    public void setRegistro(String registro) {
        this.registro = registro;
    }

    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getFumante() {
        return this.fumante;
    }

    public void setFumante(String fumante) {
        this.fumante = fumante;
    }

    public String getPai() {
        return this.pai;
    }

    public void setPai(String pai) {
        this.pai = pai;
    }

    public String getMae() {
        return this.mae;
    }

    public void setMae(String mae) {
        this.mae = mae;
    }
    
    

}
